#!/bin/bash

[[ -z $1 ]] && echo "Need a project name! Exiting!" && exit 1
[[ -z $2 ]] && echo "At least need one CPP file! Exiting!" && exit 1

args=("$@")
CPPFILES=""
FIRST_CPPFILE="$2"
MAKEFILE_TEMPLATE='/home/gaurav/study/ace/default_templates_for_projects/GNUmakefile.PROJECT_NAME'
ACE_SOURCE_FILE_TEMPLATE='/home/gaurav/study/ace/default_templates_for_projects/default_ace_source_template_with_ACE_NTRACE_0.cpp'

project_path=$(pwd)
project_name="${args[0]}"
#project_make="$project_path/GNUmakefile.${project_name}"
project_make=GNUmakefile.${project_name}

for ((i=1; i <= $#-1 ; i++)); do CPPFILES="${CPPFILES} ${args[$i]}"; done

echo
echo "PROJECT_NAME: [$project_name]"
echo "FILES ARE: [$CPPFILES]"

cp $MAKEFILE_TEMPLATE $project_make

#cp $ACE_SOURCE_FILE_TEMPLATE $(pwd)/$FIRST_CPPFILE 
cp $ACE_SOURCE_FILE_TEMPLATE $FIRST_CPPFILE 

sed -i "s/PROJECT_NAME/$project_name/g"   $project_make 
sed -i "s/CPPFILES/$CPPFILES/g"           $project_make
echo "MAKEFILE created: [$project_make]"

echo ; ls -lrth $project_make $CPPFILES ; echo
